version: '3.7'
services:
  vet-services-db:
    image: mysql:5.7
    container_name: "vet-services-db"
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql-init.sql:/data/application/init.sql

#  audit-db:
#    image: mongo:latest
#    container_name: "audit-db"
#    ports:
#      - 27017:27017
#    command: mongod
#    environment:
#      - MONGO_DATA_DIR=/data/db
#      - MONGO_LOG_DIR=/dev/null
#      - MONGODB_USER="user"
#      - MONGODB_PASS="pass"

volumes:
  my-db: