version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: "mysql"
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql-init.sql:/data/application/init.sql

  audit-db:
    image: mongo:latest
    container_name: "audit-db"
    ports:
      - 27017:27017
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - mongo-volume:/data/db

  appointment-service:
    image: appointment-service:1
    container_name: appointment-service
    ports:
      - '8080:80'
    expose:
      - '8080'

  logging-service:
    image: logging-service:1
    container_name: logging-service
    ports:
      - '8081:80'
    expose:
      - '8081'

volumes:
  my-db:
  mongo-volume: